[package]
name = 'LiquidswapLP'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0x8aa500cd155a6087509fa84bc7f0deed3363dd253ecb62b2f110885dacf01c67"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "25696fd266498d81d346fe86e01c330705a71465"
subdir = "aptos-move/framework/move-stdlib"

