[package]
name = 'LiquidswapInit'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap = "0x4e9fce03284c0ce0b86c88dd5a46f050cad2f4f33c4cdd29d98f501868558c81"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "25696fd266498d81d346fe86e01c330705a71465"
subdir = "aptos-move/framework/aptos-framework"
